---
# Configuration for BlockSniper: An innovative worldedit plugin by Sandertv.

# Maximum radius for shapes/types, it is recommended to keep this number below 20 to prevent server freezes and lag.
Maximum-Radius: 10

# Maximum undo stores to save, old ones will get destroyed automatically. Setting this number too high could result in lag or data loss.
Maximum-Undo-Stores: 7

# Language in which messages are displayed. Available languages:
# en (English), nl (Dutch), de (German)
Message-Language: ""
...