---
# Configuration for BlockSniper: A WorldEdit plugin for PocketMine.

# Internal Property: Do not change.
Configuration-Version: "2.5.0"

# Whether to auto-update configuration when a new version is found.
Auto-Configuration-Update: true

# Language in which messages are displayed. Available languages:
# en (English), nl (Dutch), ko (Korean), fr (French), zh (Simplified Chinese), zh-hant (Traditional Chinese)
Message-Language: ""

# Item ID of the item that is used to brush. (Golden carrot by default)
Brush-Item: 396

# Maximum size for shapes/types and cloning.
Maximum-Size: 30

# Maximum undo and redo stores to save, old ones will get destroyed automatically. Setting this number too high could result in lag or data loss.
Maximum-Undo-Stores: 15

# Whether to open the GUI automatically when switching hotbar slot to one containing the brush item.
Open-Gui-Automatically: true

# Whether to reset the size, or make it remain the current size when smallest size with decrement brush is reached.
Reset-Decrement-Brush: true

# Whether to save Brush properties of players after server restart, or dispose them.
Save-Brush-Properties: true

# Whether to drop the plants when using LeafBlower brush, or dispose the items.
Drop-Leafblower-Plants: true

# The size above which modifications get executed asynchronously, meaning it won't get executed on the main thread.
Asynchronous-Operation-Size: 15

# Whether to
MyPlot-Support: false
...
